language: php
sudo: false

php:
  - 5.6
  - 7.1
  - 7.3

before_install:
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then rm phpunit.xml; fi;'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then mv phpunit.hhvm.xml phpunit.xml; fi;'

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit

