language: php
sudo: false

php:
  - 7.1
  - 7.3

install:
  - pecl install pcov
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit -c ./phpunit.xml
  - bash <(curl -s https://codecov.io/bash)
